#!/bin/bash

# Construct pretty html renderings of the heap, before and after ses.

cd ../..

./save_snapshots.sh

../obj/s5.d.byte -load init.heap -print-html > ses/ses-pages/init-heap.html

../obj/s5.d.byte -load init.heap -load ses.heap -print-ses-html > ses/ses-pages/ses-heap.html

#../../../obj/s5.d.byte -load init.heap -load seseval.heap -print-ses-html > seseval-heap.html
