#!/bin/bash

# Take two snapshots: one right after s5 initialization, and one right after
# ses initialization. Save them in init.heap and ses.heap.

cd ../../

echo "___takeS5Snapshot()" | ./s5_take_snapshot ses/ses-pages/init.heap

(cat ses/es-lab-tests/initSESPlus.js; echo "___takeS5Snapshot();") | ./s5_take_snapshot ses/ses-pages/ses.heap

cd ses/ses-pages/