#!/bin/bash

TMP=`mktemp -t js.XXXXXX`
if [ $# -eq 0 ]; then
  cat>$TMP
else
  TMP=$1
fi

../bin/js json_print.js $TMP > $TMP.ast
ocamlrun ../obj/s5.d.byte -desugar $TMP.ast \
        -json ../tests/desugar.sh -env ../envs/es5.env \
        -no-stack-trace -eval 
EX=$?
rm $TMP.ast

exit $EX