#!/bin/bash

# use: s5 JSFILE OPTIONS_TO_MAIN
# e.g. s5 test.js -eval
# e.g. s5 stdin -eval

TMP=`mktemp -t js.XXXXXX`
if [ $1 == "stdin" ]; then
  cat>$TMP
  JSFILE=$TMP
else
  JSFILE=$1
fi

ocamlrun ../obj/s5.d.byte \
  -desugar $JSFILE \
  -env ../envs/regexp.env -apply \
  -desugar ../lib/js-regexp/regexp.js -to-env -apply \
  -env ../envs/json.env -apply \
  -desugar ../lib/json/json_parse.js -to-env -apply \
  -desugar ../lib/json/json2.js -to-env -apply \
  -internal-env env-vars -apply \
  -env ../envs/es5.env -apply \
  ${@:2}

EX=$?
rm $TMP

exit $EX
