#!/bin/bash

TMP=`mktemp -t js.XXXXXX`
if [ $# -eq 0 ]; then
  cat>$TMP
else
  TMP=$1
fi

../bin/js json_print.js $TMP > $TMP.ast
ocamlrun ../obj/s5.d.byte -desugar $TMP.ast -print es5 \
        -json ../src/desugar.sh -env ../envs/es5.env \
        -eval
#rm $TMP.ast
