#!/bin/bash

TMP=`mktemp -t js.XXXXXX`
if [ $# -eq 0 ]; then
  cat>$TMP
else
  TMP=$1
fi

RETMP=`mktemp -t js.XXXXXX`

../bin/js json_print.js $TMP > $TMP.ast
ocamlrun ../obj/s5.d.byte -no-stack-trace -desugar $TMP.ast \
        -json ../tests/desugar.sh -env ../envs/es5.env \
        -eval 
EX=$?
rm $TMP.ast
rm -f /tmp/js.*

exit $EX
