#!/bin/bash

TMP=`mktemp -t js.XXXXXX`
if [ $# -eq 0 ]; then
  cat>$TMP
else
  TMP=$1
fi

RETMP=`mktemp -t js.XXXXXX`

../bin/js json_print.js $TMP > $TMP.ast
ocamlrun ../obj/s5.d.byte -set-json ../tests/desugar.sh \
  -js $TMP.ast -js-to-s5 \
  -env ../envs/es5.env -apply \
  -eval
EX=$?
rm $TMP.ast
rm -f /tmp/js.*

exit $EX
