#!/bin/bash

# the file is located in tests/optimization
# always suppose the running directory is in tests

echo "get argument $@"
if [ -x $2 ]
then
    echo "$0 <jsfile> <optimization>"
    exit 1
fi

DIR=`dirname $0`
cd $DIR/..

marshalled=`mktemp -t s5.XXXXXX`
jsfile=$1
shift 2
rest=$@


# get the es5id
cat $jsfile
esid=`grep 'es5id' $jsfile | sed -n 's/es5id: \(.*\)$/\1/p'`
echo "esid: $esid"


# run through optimization phases and collect nodes.
# marshal the optimized s5 code to a file for performance.
ocamlrun ../obj/s5.d.byte \
  -desugar $jsfile \
  -internal-env env-vars -apply \
  -env ../envs/es5.env -apply \
  $rest \
  -save-s5 $marshalled > $esid.output

# load the marshalled file and do evaluation
ocamlrun ../obj/s5.d.byte \
  -load-s5  $marshalled\
  -eval-s5

EX=$?
rm $TMP

exit $EX
