#!/bin/bash

# Save a snapshot of the state of s5 after running some javascript code
# use: ./s5_save_snapshot inputfile.js outputfile.heap

TMP=`mktemp -t js.XXXXXX`
JSFILE=$1
OUTFILENAME=$2

RETMP=`mktemp -t js.XXXXXX`
../bin/js json_print.js ../lib/js-regexp/regexp.js > $RETMP

JSONLIB=`mktemp -t js.XXXXXX`
cat ../lib/json/json2.js ../lib/json/json_parse.js > $JSONLIB

JSONTMP=`mktemp -t js.XXXXXX`
../bin/js json_print.js $JSONLIB > $JSONTMP

../bin/js json_print.js $JSFILE > $TMP.ast
ocamlrun ../obj/s5.d.byte \
\
  -js $TMP.ast -js-to-s5 \
  -env ../envs/regexp.env -apply \
  -js $RETMP -js-to-s5 -to-env -apply \
  -env ../envs/json.env -apply \
  -js $JSONTMP -js-to-s5 -to-env -apply \
  -internal-env env-vars -apply \
  -env ../envs/es5.env -apply \
  -eval -gc -save $OUTFILENAME

EX=$?
rm $TMP
rm $TMP.ast
rm $RETMP
rm $JSONLIB
rm $JSONTMP

exit $EX
